### ISSUE TITLE
regarding Tesla P100 GPU

### ISSUE THREAD

**Issue by ashish-roopan** [YuvalNirkin/fsgan#43]
Is there a way to getTesla P100 GPU on colab other than factory resetting runtime?I tried resetting runtime many times but I am always getting Tesla K80 .I am getting CUDA out of memory error for some videos.
I tried reducing batch_size and segment_batch_size but the error persists.
Please look into this matter.

**Comment by YuvalNirkin** [comment]
Maybe Google are running out of those for the colab.
Anyway adding "det_batch_size=4" should solve the issue.

**Comment by ashish-roopan** [comment]
I've replaced all  ```det_batch_size=d('det_batch_size')```  with ```det_batch_size=4``` in the **/content/projects/fsgan/inference/swap.py** file.But I am still getting the **CUDA out of memory** error.It worked fine with the initial source/target video given with the notebook.The error is happening with a 10 sec video I downloaded from youtube.


![Screenshot from 2020-06-21 00-20-53](https://user-images.githubusercontent.com/40851494/85209440-ac263a80-b355-11ea-9f32-4397baf36cd3.png)

**Comment by ashish-roopan** [comment]
Found a quick hack.We can run this notebook on Kaggle Kernel on P100 GPU.
